<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class AdvertPost extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'category_id'=>'required',
            'url'=>'nullable',
            'pic'=>'required',
            'type'=>'required',
            'detail'=>'nullable',
            'product_id'=>'nullable',
            'id'=>'nullable'
        ];
    }
    public function messages()
    {
        return [
          'category_id.required'=>'',
          'pic.required'=>'',
          'type.required'=>'',
          'product_id.nullable'=>'',
        ];
//        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
