<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ApplyPost extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'name'=>'required',
            'phone'=>'required',
            'city'=>'required',
            'storeName'=>'required',
            'type'=>'required',
            'category'=>'required',
            'notifyId'=>'required',
            'id'=>'nullable',
            'picture'=>'nullable'
        ];
    }
    public function messages()
    {
        return [
            'name.required'=>getRequestMessage('nameRequired'),
            'phone.required'=>getRequestMessage('phoneRequired'),
            'city.required'=>getRequestMessage('cityRequired'),
            'storeName.required'=>getRequestMessage('storeNameRequired'),
            'type.required'=>getRequestMessage('typeRequired'),
            'category.required'=>getRequestMessage('categoryRequired'),
            'notifyId.required'=>getRequestMessage('notifyIdRequired')
        ];
//        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
