<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class LoginPost extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'username'=>'required',
            'password'=>'required|min:6'
        ];
    }
    public function messages()
    {
        return [
            'username.required'=>getRequestMessage('usernameRequired'),
            'password.required'=>getRequestMessage('passwordRequired'),
            'password.min'=>getRequestMessage('passwordMin')
        ];
//        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
