<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class WXLogin extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'code'=>'required',
            'iv'=>'required',
            'encryptedData'=>'required'
        ];
    }
    public function messages()
    {
        return [
            'code.required'=>getRequestMessage('codeRequired'),
            'iv.required'=>getRequestMessage('ivRequired'),
            'encryptedData.required'=>getRequestMessage('encryptedDataRequired')
        ];
//        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
