<?php

namespace App\Modules\SettleApply\Requests;

use Illuminate\Foundation\Http\FormRequest;

class SettleApplyPost extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'name'=>'required',
            'phone'=>'required',
            'city'=>'required|integer',
            'storeName'=>'required',
            'type'=>'required|integer',
            'category'=>'required|array',
            'category.*'=>'required|integer',
            'notifyId'=>'required',
        ];
    }
    public function messages()
    {
        return [
            'name.required'=>getRequestMessage('nameRequired'),
            'phone.required'=>getRequestMessage('phoneRequired'),
            'city.required'=>getRequestMessage('cityRequired'),
            'city.integer'=>getRequestMessage('cityInteger'),
            'storeName.required'=>getRequestMessage('storeNameRequired'),
            'type.required'=>getRequestMessage('typeRequired'),
            'type.integer'=>getRequestMessage('typeInteger'),
            'category.required'=>getRequestMessage('categoryRequired'),
            'category.*.required'=>getRequestMessage('category*Required'),
        ];
//        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
